[package]
name = "SAFE"
version = "0.1.0"
type = "lib"
authors = ["Gnosis Guild"]
license = "MIT"

[dependencies]
poseidon2 = { tag = "v0.1.0", git = "https://github.com/ozgurarmanc/noir-poseidon", directory = "poseidon2"}
