[package]
name = "SAFE"
version = "0.1.0"
type = "lib"
authors = ["Gnosis Guild"]
license = "MIT"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
poseidon2 = { tag = "v0.4.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2"}
